### ISSUE TITLE
Initial production rollout checklist

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/backend-replacement#24]
- [x] Add order recording (#8 -> #25)
- [x] Enable HTTPS
- [x] Deploy code on a separate instance (clean-slated staging instance for production)
- [ ] Add error logging with Sentry or rollbar (#15)
- [x] Update live interface config
- [x] Fix contract events backfill
- [x] Backfill some contract events
- [x] Verify stable (12-24 hrs) and fix bugs, if any (#28, #29, #30, and counting!)
- [x] Add ticker (#18)
- [ ] Add rate limiting
- [x] Announce to community

**Comment by JonathonDunford** [comment]
We should probably do something to limit API requests so we don't get spammed to death immediately.

Maybe something that checks for requests from our official site, grants it unlimited access, and gives all others limited access for the time being.
